### ISSUE TITLE
The Telescope buffer of Notion doesn't show anything

### ISSUE THREAD

**Issue by brianhuster** [Al0den/notion.nvim#24]
**Describe the bug**
I have installed the plugin, and I have `Notion setup` and have pasted my API key, and it seems successful (the command `Notion setup` now says `Status operational`. However, when I run `Notion`, a Telescope window show up, but with no content

**To Reproduce**
1. Install the plugin using lazy.nvim (I copied the table in this Readme, no modification).
2. Run `Notion setup` and paste Notion API ky
3. Run Notion
4. See that the showing Telescope window doesn't show anything

**Expected behavior**
It should show something

**Screenshots**
![image](https://github.com/user-attachments/assets/0ddaa97b-2135-49dc-8e59-abc0c8affdb8)

**Desktop (please complete the following information):**
 - OS: Kubuntu 24.04.01
 - Browser : don't know how it's relevant, but Firefox
 - Version : sorry, version of what?

**Smartphone (please complete the following information):**
 Not relevant 

**Additional context**

**Comment by Al0den** [comment]
Hello,
This is probably because you didnt give the API key a specific notion workspace access.
Just to confirm, could you verify that when running :lua print(require"notion'".raw()) it has content?
If it doesnt contain sensitive info, you canb share it to me.
Thanks!

**Comment by brianhuster** [comment]
This is the result of the command

`{"object":"list","results":[],"next_cursor":null,"has_more":false,"type":"page_or_database","page_or_database":{},"request_id":"2a190f1f-05e0-467c-99b3-1f55711dcbf3"}`

I'm not sure how I can give it notion workspace access, I only see these options
![image](https://github.com/user-attachments/assets/faad09aa-43ab-4470-b9bd-02a1dec25e53)

**Comment by phcerdan** [comment]
Facing exactly the same issue, with all the described steps, including the empty:
`:lua print(require"notion'".raw()) `

Same API integration options and chosen a workspace in the integration.
When choosing the type of integration, I kept the default `internal` option.

**Comment by Al0den** [comment]
Looking at the output of `notion.raw()`, it seems it cannot access your Notion integration. Note that raw indeed contains all the data. Trying phcerdan's solution should fix this.

It does feel odd that adding a page is necessary, though. I'll take a closer look.

**Comment by Al0den** [comment]
Update on that, it is intended behavior of the notion API. I'll close this, but if you run into any other issues feel free to open a new ticket!

**Comment by jonathanmorris180** [comment]
To add clarity for anyone else experiencing this, you need to authorize specific pages for them to show up as available: https://developers.notion.com/docs/authorization#integration-permissions

This should probably be added to the documentation. Thanks for the plugin!

**Comment by brianhuster** [comment]
Thank you. Now I have given access to my page. Running `:=vim.json.decode(require'notion'.raw())` show this
```lua
{
  has_more = false,
  next_cursor = vim.NIL,
  object = "list",
  page_or_database = vim.empty_dict(),
  request_id = "b9f74986-b241-42d8-9675-03b603cfeecf",
  results = { {
      archived = false,
      cover = vim.NIL,
      created_by = {
        id = "d945e250-b792-4d75-9f23-534bb38c6b32",
        object = "user"
      },
      created_time = "2024-06-27T16:31:00.000Z",
      icon = vim.NIL,
      id = "73634a70-5ecc-4feb-8d4e-1e891f3f2a21",
      in_trash = false,
      last_edited_by = {
        id = "d945e250-b792-4d75-9f23-534bb38c6b32",
        object = "user"
      },
      last_edited_time = "2025-02-01T02:03:00.000Z",
      object = "page",
      parent = {
        type = "workspace",
        workspace = true
      },
      properties = {
        title = {
          id = "title",
          title = { {
              annotations = {
                bold = false,
                code = false,
                color = "default",
                italic = false,
                strikethrough = false,
                underline = false
              },
              href = vim.NIL,
              plain_text = "Câu 2 : Vai trò của C.Mác và Ăng-ghen đối với sự ra đời của chủ nghĩa xã hội khoa học",
              text = {
                content = "Câu 2 : Vai trò của C.Mác và Ăng-ghen đối với sự ra đời của chủ nghĩa xã hội khoa học",
                link = vim.NIL
              },
              type = "text"
            } },
          type = "title"
        }
      },
      public_url = vim.NIL,
      url = "https://www.notion.so/C-u-2-Vai-tr-c-a-C-M-c-v-ng-ghen-i-v-i-s-ra-i-c-a-ch-ngh-a-x-h-i-khoa-h-c-73634a705ecc4feb8d4e1e891f3f2a21"
    } },
  type = "page_or_database"
}
```

But when I run `:Notion`, the floating window still doesn't show anything
